site_name: DITA-OT MkDocs Demo

theme:
  name: material

plugins:
  - search
  - section-index

nav:
  - 'DITA Open Toolkit 4.0': 'index.md'
  - 'Release Notes':
    - 'release-notes/index.md'
    - 'Release history': 'topics/release-history.md'
  - 'Installing DITA-OT':
    - 'topics/installing-client.md'
    - 'Prerequisite software': 'topics/prerequisite-software.md'
    - 'Checking the version': 'topics/determining-version-of-ditaot.md'
    - 'Building output': 'topics/first-build-using-dita-command.md'
    - 'Installing via Homebrew': 'topics/installing-via-homebrew.md'
  - 'Building output': 
    - 'topics/building-output.md'
    - 'Using the dita command': 'topics/build-using-dita-command.md'
