site_name: DITA-OT MkDocs Demo

theme:
  name: material
  features:
    - navigation.indexes 

nav:
  - 'DITA Open Toolkit 4.0': 'index.md'
  - 'Release Notes':
    - 'release-notes/index.md'
    - 'Release history': 'topics/release-history.md'
